import { z } from "zod";

/**
 * The single source of truth for the shape of a tool record.
 *
 * This Zod schema drives three things, so they can never drift:
 *   - the TypeScript types the site compiles against (`z.infer`, below);
 *   - the JSON Schema published beside the skill (generated by `mise run gen:schema`);
 *   - runtime validation of `data/context-reduction-tools.json` (`mise run validate`).
 *
 * Zod is a build/CI-time dependency only - the site imports the inferred *types*
 * from here (erased at compile time), never the schema values, so Zod is not
 * shipped to the browser.
 *
 * Records are strongly typed: enums for closed vocabularies, numbers for counts
 * and trend, and objects for fields that carry more than one datum. Free-text
 * detail is preserved verbatim in `notes`/`note`/`detail`/`rationale` so nothing
 * is lost and the table and CSV export can reproduce the original display.
 */

/** Primary display layer. Group by prefix; several raw strings collapse in the UI. */
export const layerSchema = z.enum([
  "Shell output",
  "All tool output",
  "Static context injection (push model)",
  "Conversation history management",
  "Personal knowledge retrieval",
  "Library documentation retrieval",
  "Codebase understanding & onboarding",
  "Code navigation",
  "Architecture violation detection (trust-first)",
  "Architecture violation detection",
  "MCP definition tokens",
  "Cross-session governance & reasoning capture",
  "Cross-session governance",
  "Response verbosity + memory compression",
  "Config stack audit & optimisation",
  "Config stack audit",
  "Agent safety enforcement",
  "Tabular data retrieval",
  "Agent runtime & context orchestration",
  "Universal context compression middleware",
  "Reference resource (curated list)",
  "Agent memory persistence",
  "Code generation minimalism (YAGNI enforcement)",
]);

/** Normalised implementation language. `none` for built-ins / skill files / curated lists. */
export const runtimeLanguageSchema = z.enum([
  "rust",
  "python",
  "typescript",
  "javascript",
  "node",
  "go",
  "powershell",
  "shell",
  "lua",
  "gleam",
  "none",
]);

/** Activity band, driving the colour and the activity filter. */
export const activityBandSchema = z.enum([
  "active",
  "stable",
  "slowing",
  "early",
  "dormant",
  "none",
]);

/** Conflict severity between this tool and others. */
export const conflictSeveritySchema = z.enum(["hard", "soft", "either-or", "stackable", "none"]);

/** Adoption decision. `add-if` is "Add if you use [X]". */
export const verdictDecisionSchema = z.enum([
  "best",
  "add",
  "add-if",
  "either-or",
  "watch",
  "reference",
  "drop",
]);

/** ISO date, YYYY-MM-DD. */
const isoDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "must be an ISO date (YYYY-MM-DD)");

/** Where a cited source sits on the evidence spectrum. */
export const evidenceTypeSchema = z.enum([
  "source-code",
  "official-docs",
  "readme",
  "release",
  "search",
  "third-party",
]);

/** Status of a claim once its sources are weighed. */
export const evidenceStatusSchema = z.enum(["confirmed", "caveated", "refuted", "unverified"]);

/** Proof-ledger decision for a headline / benchmark claim. */
export const proofLedgerSchema = z.enum(["PROVEN", "SUPPORTED", "OPEN", "REJECTED"]);

/** Source types stronger than a README mention (drives the code-beats-docs rule). */
const STRONG_EVIDENCE: readonly string[] = ["source-code", "official-docs", "release"];

/**
 * A `source-code` citation must be a permalink pinned to a commit SHA (not a moving
 * branch) with a line anchor, on a recognised code host: GitHub/Gitea (`/blob/<sha>/`),
 * GitLab (`/-/blob/<sha>/`), or Codeberg/Gitea (`/src/commit/<sha>/`). A hex ref rejects
 * branch names; the `#L` anchor rejects repo-root and whole-file URLs. Whole-file or
 * absence claims (e.g. a LICENSE file, "no telemetry") have no single line and belong
 * under `official-docs`/`release`, not `source-code`.
 *
 * Enforced by `mise run validate` only. It does NOT reach the published JSON Schema:
 * `z.toJSONSchema` drops `superRefine` (see scripts/gen-schema.ts), as it already does
 * for the code-beats-docs rule below.
 */
const SOURCE_CODE_PERMALINK =
  /^https?:\/\/[^/\s]+\/\S+?(?:\/blob\/|\/-\/blob\/|\/src\/commit\/)[0-9a-f]{7,40}\/\S+#L\d+(?:-L?\d+)?$/i;

/** A single citation. `url` should be a commit-SHA permalink, not a moving branch. */
export const evidenceSourceSchema = z
  .object({
    url: z.url(),
    /** The cited text, quoted verbatim from the source. */
    quote: z.string().min(1),
    /** Date the source was checked, ISO YYYY-MM-DD. */
    checkedOn: isoDate,
    evidenceType: evidenceTypeSchema,
  })
  .strict()
  .superRefine((s, ctx) => {
    if (s.evidenceType === "source-code" && !SOURCE_CODE_PERMALINK.test(s.url)) {
      ctx.addIssue({
        code: "custom",
        message:
          "a 'source-code' source needs a commit-SHA permalink with a line anchor (e.g. .../blob/<sha>/path#L42); a whole-file or licence claim belongs under 'official-docs' or 'release'",
        path: ["url"],
      });
    }
  });

/**
 * Evidence attached to a claim: its status and the sources behind it. A
 * `confirmed` claim needs at least one source rooted in code, official docs, or
 * a release; README-only backing tops out at `caveated` (code-beats-docs).
 */
export const evidenceSchema = z
  .object({
    status: evidenceStatusSchema,
    sources: z.array(evidenceSourceSchema),
  })
  .strict()
  .superRefine((e, ctx) => {
    if (e.status !== "unverified" && e.sources.length === 0) {
      ctx.addIssue({
        code: "custom",
        message: "a claim that is not 'unverified' must cite at least one source",
        path: ["sources"],
      });
    }
    if (
      e.status === "confirmed" &&
      !e.sources.some((s) => STRONG_EVIDENCE.includes(s.evidenceType))
    ) {
      ctx.addIssue({
        code: "custom",
        message:
          "a 'confirmed' claim needs a source-code, official-docs, or release source (README alone is 'caveated')",
        path: ["status"],
      });
    }
  });

/** A standalone claim that maps to no record field (e.g. a benchmark number). */
export const extraClaimSchema = z
  .object({
    kind: z.enum(["benchmark", "feature"]),
    /** Short label, e.g. "LoCoMo accuracy@1", "offline operation". */
    label: z.string().min(1),
    /** Falsifiable restatement of the claim. */
    statement: z.string().min(1),
    evidence: evidenceSchema,
    proofLedger: proofLedgerSchema.optional(),
  })
  .strict()
  .superRefine((c, ctx) => {
    if (c.kind === "benchmark" && !c.proofLedger) {
      ctx.addIssue({
        code: "custom",
        message: "a benchmark claim must carry a proofLedger decision",
        path: ["proofLedger"],
      });
    }
  });

export const runtimeSchema = z
  .object({
    languages: z.array(runtimeLanguageSchema).min(1),
    detail: z.string().optional(),
    evidence: evidenceSchema.optional(),
  })
  .strict();

export const licenceSchema = z
  .object({
    /** SPDX-ish identifier, e.g. "MIT", "AGPL-3.0", "PolyForm Noncommercial". */
    spdx: z.string().min(1),
    /** Optional caveat, e.g. missing LICENSE file or a dual-licence note. */
    warning: z.string().optional(),
    evidence: evidenceSchema.optional(),
  })
  .strict();

export const activitySchema = z
  .object({
    contributors: z.number().int().nonnegative().optional(),
    /**
     * The newest upstream release observed on the evidence `checkedOn` date, i.e.
     * the value the freshness check diffs against. This is an observation of
     * upstream, never a recommended pin, so the drift comparison converges once a
     * human re-records it. Must be a comparable version string (e.g. "v1.2.3").
     */
    latestVersion: z.string().optional(),
    releaseCount: z.number().int().nonnegative().optional(),
    /** Date of the latest release, ISO YYYY-MM-DD. */
    releasedOn: isoDate.optional(),
    corroboration: z.string().optional(),
    /** Full free-text detail, preserved verbatim. */
    notes: z.string().optional(),
    evidence: evidenceSchema.optional(),
  })
  .strict();

export const activityStatusSchema = z
  .object({
    band: activityBandSchema,
    /** Display label without the band emoji, e.g. "Hyper-active", "Active (solo)". */
    label: z.string().min(1),
  })
  .strict();

export const conflictSchema = z
  .object({
    severity: conflictSeveritySchema,
    /** Names of the tools this one conflicts or overlaps with. */
    projects: z.array(z.string()),
    /** Full free-text explanation, preserved verbatim. */
    note: z.string().optional(),
    evidence: evidenceSchema.optional(),
  })
  .strict();

export const verdictSchema = z
  .object({
    decision: verdictDecisionSchema,
    /** The reasoning that followed the decision, preserved verbatim. */
    rationale: z.string(),
    /**
     * Source-verified backing for the decision. Optional so the 79 legacy records
     * stay valid; Phase 2 backfills it for the tools behind published recommendations.
     */
    evidence: evidenceSchema.optional(),
  })
  .strict()
  .superRefine((v, ctx) => {
    // A recommendation-grade verdict cannot stand on evidence we have refuted or
    // never verified. This routes an honest evidence downgrade back to failing here,
    // rather than silently keeping a "best" call behind a weak citation.
    if (
      (v.decision === "best" || v.decision === "either-or") &&
      (v.evidence?.status === "refuted" || v.evidence?.status === "unverified")
    ) {
      ctx.addIssue({
        code: "custom",
        message: "a 'best'/'either-or' verdict may not carry 'refuted' or 'unverified' evidence",
        path: ["evidence", "status"],
      });
    }
  });

export const toolSchema = z
  .object({
    /**
     * Immutable, URL-safe stable identifier, assigned once and never regenerated
     * from the display name. Freshness prompts and issues key on this, so a later
     * rename of `tool` cannot orphan them. Seeded from `toolSlug(tool)` on first add.
     */
    id: z.string().min(1),
    tool: z.string().min(1),
    githubUrl: z.url(),
    layer: layerSchema,
    whatItDoes: z.string(),
    conflict: conflictSchema,
    runtime: runtimeSchema,
    requirements: z.string(),
    /**
     * True when the tool needs model/API calls or external infra to run. A typed
     * flag (not a glyph in `requirements`) so the UI derives the warning from data,
     * never by parsing prose. Drives the "needs model or infra" badge and filter.
     */
    requiresExternal: z.boolean().default(false),
    licence: licenceSchema,
    /** Verified star count; null when unknown or not applicable (built-ins). */
    stars: z.number().int().nonnegative().nullable(),
    /** Signed 30-day trend as a percentage; null when unknown. Sign carries direction. */
    trend: z.number().nullable(),
    activity: activitySchema,
    activityStatus: activityStatusSchema,
    verdict: verdictSchema,
    decisionRule: z.string(),
    /** Standalone benchmark / feature claims that map to no field above. */
    extraClaims: z.array(extraClaimSchema).optional(),
  })
  .strict()
  .superRefine((t, ctx) => {
    // Enforce DESIGN.md's "No emoji as status" rule at the data contract: the
    // display prose fields must not carry emoji or status glyphs (status rides on
    // typed fields and the dot/pill components). Evidence quotes are exempt: they
    // are verbatim source excerpts.
    const EMOJI = /\p{Extended_Pictographic}/u;
    const fields: [string[], string | undefined][] = [
      [["whatItDoes"], t.whatItDoes],
      [["requirements"], t.requirements],
      [["decisionRule"], t.decisionRule],
      [["conflict", "note"], t.conflict.note],
      [["verdict", "rationale"], t.verdict.rationale],
      [["activity", "notes"], t.activity.notes],
      [["licence", "warning"], t.licence.warning],
      [["runtime", "detail"], t.runtime.detail],
    ];
    for (const [path, val] of fields) {
      if (val && EMOJI.test(val)) {
        ctx.addIssue({
          code: "custom",
          message: `${path.join(".")} must not contain emoji or status glyphs; carry status in a typed field (DESIGN.md: No emoji as status)`,
          path,
        });
      }
    }
  });

export const metaSchema = z
  .object({
    last_updated: isoDate,
    stars_verified: isoDate,
    tool_count: z.number().int().nonnegative(),
  })
  .strict();

export const datasetSchema = z
  .object({
    meta: metaSchema,
    tools: z.array(toolSchema),
  })
  .strict()
  .refine((d) => d.meta.tool_count === d.tools.length, {
    message: "meta.tool_count must equal tools.length",
    path: ["meta", "tool_count"],
  })
  .refine((d) => new Set(d.tools.map((t) => t.tool)).size === d.tools.length, {
    message: "tool names must be unique",
    path: ["tools"],
  })
  .refine((d) => new Set(d.tools.map((t) => t.id)).size === d.tools.length, {
    message: "tool ids must be unique",
    path: ["tools"],
  });

/** One alternative to a recommendation's pick, with the condition it wins under. */
export const recommendationAlternativeSchema = z
  .object({
    id: z.string().min(1),
    /** The condition under which this alternative is preferable, e.g. "a zero-dep bundle is required". */
    when: z.string().min(1),
  })
  .strict();

/**
 * A cross-tool "use this, not that" recommendation, keyed to an existing `layer`
 * (optionally a named sub-group within a broad layer). Intra-record shape is
 * checked here; the cross-store invariants (ids exist, belong to the layer, the
 * pick is a `best`/`either-or` verdict backed by source-verified evidence, and
 * member sets are disjoint per layer) live in scripts/validate, which can see the
 * tool store this schema cannot.
 */
export const recommendationSchema = z
  .object({
    id: z.string().min(1),
    layer: layerSchema,
    /** Optional label when splitting a broad layer into sub-groups (e.g. "AST knowledge-graph"). */
    group: z.string().min(1).optional(),
    /** Tool ids in this recommendation; exactly the pick plus the alternatives. */
    members: z.array(z.string().min(1)).min(2),
    /** The default recommendation: a member id (must hold a best/either-or verdict, checked in validate). */
    pick: z.string().min(1),
    alternatives: z.array(recommendationAlternativeSchema),
    rationale: z.string().min(1),
    evidence: evidenceSchema.optional(),
  })
  .strict()
  .superRefine((r, ctx) => {
    const altIds = r.alternatives.map((a) => a.id);
    if (altIds.includes(r.pick)) {
      ctx.addIssue({
        code: "custom",
        message: "pick must not also be an alternative",
        path: ["pick"],
      });
    }
    if (new Set(altIds).size !== altIds.length) {
      ctx.addIssue({ code: "custom", message: "duplicate alternative id", path: ["alternatives"] });
    }
    // members must equal {pick} ∪ alternatives exactly: no member the head-to-head
    // ignores, and no pick/alternative missing from the member list.
    const mentioned = new Set([r.pick, ...altIds]);
    const memberSet = new Set(r.members);
    if (r.members.some((m) => !mentioned.has(m))) {
      ctx.addIssue({
        code: "custom",
        message: "every member must be the pick or an alternative",
        path: ["members"],
      });
    }
    if ([...mentioned].some((m) => !memberSet.has(m))) {
      ctx.addIssue({
        code: "custom",
        message: "pick and every alternative must be listed in members",
        path: ["members"],
      });
    }
  });

export const recommendationsFileSchema = z
  .object({ recommendations: z.array(recommendationSchema) })
  .strict();

export type Layer = z.infer<typeof layerSchema>;
export type RuntimeLanguage = z.infer<typeof runtimeLanguageSchema>;
export type ActivityBand = z.infer<typeof activityBandSchema>;
export type ConflictSeverity = z.infer<typeof conflictSeveritySchema>;
export type VerdictDecision = z.infer<typeof verdictDecisionSchema>;
export type Runtime = z.infer<typeof runtimeSchema>;
export type Licence = z.infer<typeof licenceSchema>;
export type Activity = z.infer<typeof activitySchema>;
export type ActivityStatus = z.infer<typeof activityStatusSchema>;
export type Conflict = z.infer<typeof conflictSchema>;
export type Verdict = z.infer<typeof verdictSchema>;
export type EvidenceType = z.infer<typeof evidenceTypeSchema>;
export type EvidenceStatus = z.infer<typeof evidenceStatusSchema>;
export type ProofLedger = z.infer<typeof proofLedgerSchema>;
export type EvidenceSource = z.infer<typeof evidenceSourceSchema>;
export type Evidence = z.infer<typeof evidenceSchema>;
export type ExtraClaim = z.infer<typeof extraClaimSchema>;
export type Tool = z.infer<typeof toolSchema>;
export type Meta = z.infer<typeof metaSchema>;
export type Dataset = z.infer<typeof datasetSchema>;
export type RecommendationAlternative = z.infer<typeof recommendationAlternativeSchema>;
export type Recommendation = z.infer<typeof recommendationSchema>;
export type RecommendationsFile = z.infer<typeof recommendationsFileSchema>;
