import { z } from "zod";

/**
 * The single source of truth for the shape of a tool record.
 *
 * This Zod schema drives three things, so they can never drift:
 *   - the TypeScript types the site compiles against (`z.infer`, below);
 *   - the JSON Schema published beside the skill (generated by `mise run gen:schema`);
 *   - runtime validation of `data/context-reduction-tools.json` (`mise run validate`).
 *
 * Zod is a build/CI-time dependency only — the site imports the inferred *types*
 * from here (erased at compile time), never the schema values, so Zod is not
 * shipped to the browser.
 *
 * All fields are strings: the catalogue is free-text by design (star counts like
 * "~20" or "—", emoji-prefixed requirements, etc.).
 */
export const toolSchema = z
  .object({
    tool: z.string().min(1),
    githubUrl: z.string().min(1),
    layer: z.string().min(1),
    whatItDoes: z.string(),
    conflict: z.string(),
    runtime: z.string(),
    requirements: z.string(),
    licence: z.string(),
    stars: z.string(),
    trend: z.string(),
    activity: z.string(),
    activityStatus: z.string(),
    verdict: z.string(),
    decisionRule: z.string(),
  })
  .strict();

const isoDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "must be an ISO date (YYYY-MM-DD)");

export const metaSchema = z
  .object({
    /** When the catalogue was last touched. */
    last_updated: isoDate,
    /** Date the star counts and activity were verified (shown in the site header). */
    stars_verified: isoDate,
    /** Number of tools; must equal tools.length. */
    tool_count: z.number().int().nonnegative(),
  })
  .strict();

export const datasetSchema = z
  .object({
    meta: metaSchema,
    tools: z.array(toolSchema),
  })
  .strict()
  .refine((d) => d.meta.tool_count === d.tools.length, {
    message: "meta.tool_count must equal tools.length",
    path: ["meta", "tool_count"],
  })
  .refine((d) => new Set(d.tools.map((t) => t.tool)).size === d.tools.length, {
    message: "tool names must be unique",
    path: ["tools"],
  });

export type Tool = z.infer<typeof toolSchema>;
export type Meta = z.infer<typeof metaSchema>;
export type Dataset = z.infer<typeof datasetSchema>;
