/**
 * Generate src/styles/icons.css from the Tabler outline SVGs (MIT licensed).
 *
 * The stack-builder only uses a handful of icons, so instead of shipping the
 * full @tabler/icons-webfont (~210 kB) we inline just those glyphs as
 * mask-image data URIs. Icons render in currentColor and are sized by
 * font-size, so the existing `<i class="ti ti-x">` markup keeps working.
 *
 * Run with `mise run gen:icons` (or `bun run gen:icons`) after adding an icon
 * to the ICONS list below. Requires the @tabler/icons dev dependency for the
 * source SVGs; the generated CSS is self-contained and committed.
 */
import { readFileSync, writeFileSync } from "node:fs";

const ICONS = [
  "star",
  "x",
  "search",
  "stack-2",
  "alert-triangle",
  "plug",
  "download",
  "check",
  "external-link",
];

const SRC = "node_modules/@tabler/icons/icons/outline";
const OUT = "src/styles/icons.css";

export const encode = (svg: string): string => {
  const oneLine = svg
    .replace(/<path stroke="none"[^/]*\/>\s*/g, "")
    .replace(/stroke="currentColor"/g, 'stroke="%23000"')
    .replace(/\s+/g, " ")
    .trim();
  return oneLine.replace(/"/g, "'").replace(/</g, "%3C").replace(/>/g, "%3E").replace(/#/g, "%23");
};

let css = `/* Generated by scripts/gen-icons.ts. Do not edit by hand.
   Tabler outline icons (MIT), inlined as mask-image data URIs, replacing the
   full @tabler/icons-webfont with only the icons the stack-builder uses. */

.ti {
  display: inline-block;
  width: 1em;
  height: 1em;
  vertical-align: -0.125em;
  background-color: currentColor;
  -webkit-mask-repeat: no-repeat;
  mask-repeat: no-repeat;
  -webkit-mask-position: center;
  mask-position: center;
  -webkit-mask-size: contain;
  mask-size: contain;
}

`;

for (const name of ICONS) {
  const svg = readFileSync(`${SRC}/${name}.svg`, "utf8");
  const uri = `url("data:image/svg+xml,${encode(svg)}")`;
  css += `.ti-${name} {\n  -webkit-mask-image: ${uri};\n  mask-image: ${uri};\n}\n`;
}

writeFileSync(OUT, css);
console.log(`wrote ${OUT} (${ICONS.length} icons)`);
